version: '3.3'

services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xkmjr3m3
      POSTGRES_DB: ci-db
      POSTGRES_HOST_AUTH_METHOD: trust
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  demo-ci-proj:
    image: marael1701/demo-ci-proj
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-ci-proj
    ports:
      - "8081:8081"
    depends_on:
      - db
      - redis
    environment:
      - SERVER_PORT= 8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ci-db