version: '3.3'

services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xkmjr3m3
      POSTGRES_DB: ci-db
      POSTGRES_HOST_AUTH_METHOD: trust
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ../:/etc/nginx/conf.d/
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./redis-data:/usr/local/etc/redis/redis-data
    command: '--requirepass Uhsbp5jyDc'
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "Uhsbp5jyDc"
  demo-ci-proj:
    image: marael1701/demo-ci-proj:6efd96b3c229d6fa0c1c4c0268d53e473f82e628
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-ci-proj
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    depends_on:
      - db
      - redis
    environment:
      - SERVER_PORT= 8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ci-db

  fluentd:
    container_name: fluentd
    build:
      context: ./fluentd/
      dockerfile: Dockerfile
    volumes:
      - ./fluentd/:/fluentd/etc
    depends_on:
      - opensearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      discovery.type: single-node
      node.name: opensearch
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "7&kMHk/E}xoaD+2PEZKW"
      plugins.security.disabled: true
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

#  opensearch:
#    build:
#      context: ./opensearch/
#      dockerfile: Dockerfile
#    container_name: opensearch
#    environment:
#      discovery.type: single-node
#      node.name: opensearch
#      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
#      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "7&kMHk/E}xoaD+2PEZKW"
#    volumes:
#      - opensearch-data:/usr/share/opensearch/data
#    ports:
#      - "9200:9200"
#      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
      opensearch.username: "Admin"
      opensearch.password: "7&kMHk/E}xoaD+2PEZKW"

    depends_on:
      - opensearch
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus


  grafana:
    container_name: grafana
    build: './grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin


volumes:
  opensearch-data:
  pg-data:
  redis-data:

