apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ci-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ci-app
  minReplicas: 1
  maxReplicas: 4
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40

  behavior: 
    scaleDown: 
      stabilizationWindowSeconds: 0 
      policies: 
        - type: Percent
          value: 20
          periodSeconds: 15
    scaleUp: 
      stabilizationWindowSeconds: 0 
      policies:
        - type: Percent
          value: 40
          periodSeconds: 15
