name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21-ea
    - name: Tests execution
      run: ./gradlew test
    - name: Prepare App for image
      run: ./gradlew bootJar &&
          mkdir build-output &&
          cp build/libs/demo-ci-proj-0.0.1-SNAPSHOT.jar build-output/
    - name: LS -alrt
      run: cd build-output && ls -alrt
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push the Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{GITHUB_SHA}}
